spring:
  datasource:
    url: jdbc:postgresql://{REGION}.sql.xata.sh:5432/{DATABASE_NAME}:{BRANCH}
    username: { WORKSPACE_ID }
    password: { API_KEY }
    driver-class-name: org.postgresql.Driver